POST http://localhost:3000/api/user/login HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Ijk4OGQ1YTM3OWI3OGJkZjFlNTBhNDA5MTEzZjJiMGM3NWU0NTJlNDciLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiQXN3aW4gUmFhaiBQIFMgIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2Z5dHJhaSIsImF1ZCI6ImZ5dHJhaSIsImF1dGhfdGltZSI6MTc2NjQ3MzczOCwidXNlcl9pZCI6IlZhQjdBVm5GWXpaYmdYek9hWFpoNGlCMnNSdDIiLCJzdWIiOiJWYUI3QVZuRll6WmJnWHpPYVhaaDRpQjJzUnQyIiwiaWF0IjoxNzY2NDczNzM4LCJleHAiOjE3NjY0NzczMzgsImVtYWlsIjoiYXN3aW5yYWFqMjQwNUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiYXN3aW5yYWFqMjQwNUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.bTRULvS16COS0Cd7CyNV_wODh1zOlrXiFOOMaxaOZdXN1KaXEnUKU2zygdj7GfQHo5M026Jqr-6mTgUPkhxWIm3_Qx8aYzuveBJfZt1kj0hcjtaI7D28_Bja8Sdi5F0gBK7A_Hh5SFKcWJwONQcwLuRIjE78CfgSPXyV2cjFWPWIitQX94ewoUFYiyM4HOijhbxiKw5TwQ2d9s-tTv6XxvSc_xnrQvIKpPOMURtyO-autTAVDJBisORdQJ9eiJ0lmFC1rDfK9LaDz5VTI1EM1SOWU0yo61bBQ5w9WrPXBEM0lvJJwtqvZAogl1dGkOF-YfS13nviSQzxCVnjTOOZfw

{
   
}